blank_issues_enabled: false
contact_links:
  - name: GitHub Discussion 
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Bug Bounty Program
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
